### ISSUE TITLE
define-abbrev Error

### ISSUE THREAD

**Issue by TheWaWaR** [4d47/wren-mode.el#1]
Emacs version: **GNU Emacs 26.1**

This line does not work:
``` 
(define-abbrev wren-mode-abbrev-table "Sys" "System" nil :case-fixed)
```

**Error message:**
```
Wrong type argument: plistp, (:case-fixed)
```

**Comment by 4d47** [comment]
Thanks for the issue,

This is little harder for me to fix since I'm not really using Emacs and Wren anymore. I wrote this with Emacs 24, I think I might have tested it with Emacs 25 but I'm not sure, anyway ..

I removed the `case-fixed` property and the error is gone. If abbrev-mode is enabled you can Type `Sys.` and it will expand to `System.`.

Hope it works well for you.
